<?php

namespace AppBundle\Repository;

/**
 * ProdCategRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProdCategRepository extends \Doctrine\ORM\EntityRepository
{
}
